name: Tests
on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: hitta_ka_test
          POSTGRES_PASSWORD: "password"
        ports: ["5432:5432"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "yarn"

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: myapp
        run: |
          bin/rails db:setup

      - name: Run tests
        run: bundle exec rspec --profile 10 --format RspecJunitFormatter --out rspec.xml --format documentation

      - name: Set Blinka tag
        run: echo blinka_webhooks > ./blinka_tag

      - name: Blinka - Archive
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: blinka
          path: |
            ./rspec.xml
            ./tmp/screenshots
            ./blinka_tag
